# Generated by Django 3.1 on 2021-11-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenderRef',
            fields=[
                ('text', models.CharField(max_length=10)),
                ('gender', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(unique=True)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.genderref')),
            ],
        ),
    ]
