# Generated by Django 3.1 on 2021-11-06 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='课程名称')),
                ('price', models.IntegerField(verbose_name='课程费用')),
            ],
        ),
        migrations.CreateModel(
            name='GenderRef',
            fields=[
                ('text', models.CharField(max_length=10)),
                ('gender', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('role', models.CharField(max_length=16)),
                ('language', models.CharField(choices=[('golang', 'golang'), ('java', 'java'), ('javascript', 'javascript'), ('python', 'python')], default='python', max_length=32)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'quickstart_persons',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(unique=True)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.genderref')),
            ],
        ),
    ]
